
## Introduction to Radar Chart for ESG Ratings Comparison

Environmental, Social, and Governance (ESG) ratings are essential metrics used to evaluate a company's sustainability and ethical impact. Different rating providers, such as MSCI, Sustainalytics, and S&P Global, offer their assessments, which can sometimes diverge significantly. To visualize these differences, a radar chart (also known as a spider chart) is an effective tool.

A radar chart allows us to plot multiple variables for different entities on a single graph, making it easy to compare their performance across various dimensions. In this notebook, we will use Plotly to create a radar chart that compares the ESG ratings of two companies—Tencent, Meta—across two rating providers: MSCI, Sustainalytics and S&P Global.

The radar chart will help us identify areas where the ratings diverge and provide a clear visual representation of each company's strengths and weaknesses according to different rating providers.

In [1]:
%pip install plotly --quiet
%pip install --upgrade nbformat

Note: you may need to restart the kernel to use updated packages.
Requirement already satisfied: nbformat in /Users/chenwanqiu/Downloads/llm_esg_judge-2_/.conda/lib/python3.11/site-packages (5.10.4)
Requirement already satisfied: fastjsonschema>=2.15 in /Users/chenwanqiu/Downloads/llm_esg_judge-2_/.conda/lib/python3.11/site-packages (from nbformat) (2.21.1)
Requirement already satisfied: jsonschema>=2.6 in /Users/chenwanqiu/Downloads/llm_esg_judge-2_/.conda/lib/python3.11/site-packages (from nbformat) (4.23.0)
Requirement already satisfied: jupyter-core!=5.0.*,>=4.12 in /Users/chenwanqiu/Downloads/llm_esg_judge-2_/.conda/lib/python3.11/site-packages (from nbformat) (5.7.2)
Requirement already satisfied: traitlets>=5.1 in /Users/chenwanqiu/Downloads/llm_esg_judge-2_/.conda/lib/python3.11/site-packages (from nbformat) (5.14.3)
Requirement already satisfied: attrs>=22.2.0 in /Users/chenwanqiu/Downloads/llm_esg_judge-2_/.conda/lib/python3.11/site-packages (from jsonschema>=2.6->nbformat) (25.3.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /Users/chenwanqiu/Downloads/llm_esg_judge-2_/.conda/lib/python3.11/site-packages (from jsonschema>=2.6->nbformat) (2024.10.1)
Requirement already satisfied: referencing>=0.28.4 in /Users/chenwanqiu/Downloads/llm_esg_judge-2_/.conda/lib/python3.11/site-packages (from jsonschema>=2.6->nbformat) (0.36.2)
Requirement already satisfied: rpds-py>=0.7.1 in /Users/chenwanqiu/Downloads/llm_esg_judge-2_/.conda/lib/python3.11/site-packages (from jsonschema>=2.6->nbformat) (0.23.1)
Requirement already satisfied: platformdirs>=2.5 in /Users/chenwanqiu/Downloads/llm_esg_judge-2_/.conda/lib/python3.11/site-packages (from jupyter-core!=5.0.*,>=4.12->nbformat) (4.3.7)
Requirement already satisfied: typing-extensions>=4.4.0 in /Users/chenwanqiu/Downloads/llm_esg_judge-2_/.conda/lib/python3.11/site-packages (from referencing>=0.28.4->jsonschema>=2.6->nbformat) (4.12.2)
Note: you may need to restart the kernel to use updated packages.

In [2]:
import os
os.getcwd()

'/Users/chenwanqiu/Downloads/llm_esg_judge-2_/cookbooks'

In [3]:
import pandas as pd

# Read the ESG ratings from METADATA JSON file


esg_ratings = pd.read_json('/Users/chenwanqiu/Downloads/llm_esg_judge-2_/submission/Task1_Data/metadata.json')

print(esg_ratings.columns)

Index(['Company', 'PDF_link', 'Sector', 'MSCI', 'SPGlobal'], dtype='object')

In [4]:
esg_ratings.set_index('Company', inplace=True)

In [5]:
esg_ratings_msci=esg_ratings[['MSCI']]

esg_ratings_sp=esg_ratings[['SPGlobal']]

In [6]:
esg_ratings_msci.iloc[0]['MSCI']

{'MASI_Link': 'https://www.msci.com/our-solutions/esg-investing/esg-ratings-climate-search-tool/issuer/tencent-holdings-limited/IID000000002149109',
 'MSCI_Score': 'BBB',
 'Corporate_Behavior': 'lag',
 'Access_to_Finance': 'lag',
 'Corporate_Governance': 'average',
 'Human_Capital_Development': 'average',
 'Carbon_Emissions': 'average',
 'Privacy_Data_Security': 'lead'}

In [7]:

indicators = [
    'Corporate_Behavior', 
    # 'Access_to_Finance', 
    'Corporate_Governance', 
    'Human_Capital_Development', 
    'Carbon_Emissions', 
    'Privacy_Data_Security'
    ]

dimensions = [
    # 'Cybersecurity_and_System_Availability', 
    # 'Human_Rights', 
    'Human_Capital_Management', 
    'Business_Ethics', 
    'Climate_Strategy', 
    # 'Environmental_Policy', 
    # 'Corporate_Governance', 
    'Customer_Relations', 
    # 'Privacy_Protection'
]

In [8]:
esg_ratings_msci

                                                                       MSCI
Company
Tencent Holdings          {'MASI_Link': 'https://www.msci.com/our-soluti...
Walmart                   {'MASI_Link': 'https://www.msci.com/our-soluti...
Amazon                    {'MASI_Link': 'https://www.msci.com/our-soluti...
Exxon Mobil               {'MASI_Link': 'https://www.msci.com/our-soluti...
Apple                     {'MASI_Link': 'https://www.msci.com/our-soluti...
UnitedHealth Group        {'MASI_Link': 'https://www.msci.com/our-soluti...
UnitedHealth Group        {'MASI_Link': 'https://www.msci.com/our-soluti...
CVS Health                {'MASI_Link': 'https://www.msci.com/our-soluti...
Alphabet                  {'MASI_Link': 'https://www.msci.com/our-soluti...
McKesson                  {'MASI_Link': 'https://www.msci.com/our-soluti...
Chevron                   {'MASI_Link': 'https://www.msci.com/our-soluti...
Costco Wholesale          {'MASI_Link': 'https://www.msci.com/our-soluti...
Microsoft                 {'MASI_Link': 'https://www.msci.com/our-soluti...
Cardinal Health           {'MASI_Link': 'https://www.msci.com/our-soluti...
Cigna                     {'MASI_Link': 'https://www.msci.com/our-soluti...
Marathon Petroleum        {'MASI_Link': 'https://www.msci.com/our-soluti...
Phillips 66               {'MASI_Link': 'https://www.msci.com/our-soluti...
Valero Energy             {'MASI_Link': 'https://www.msci.com/our-soluti...
Ford Motor                {'MASI_Link': 'https://www.msci.com/our-soluti...
Home Depot                {'MASI_Link': 'https://www.msci.com/our-soluti...
General Motors            {'MASI_Link': 'https://www.msci.com/our-soluti...
JPMorgan Chase            {'MASI_Link': 'https://www.msci.com/our-soluti...
Kroger                    {'MASI_Link': 'https://www.msci.com/our-soluti...
Verizon Communications    {'MASI_Link': 'https://www.msci.com/our-soluti...
Walgreens Boots Alliance  {'MASI_Link': 'https://www.msci.com/our-soluti...
Comcast                   {'MASI_Link': 'https://www.msci.com/our-soluti...
AT&T                      {'MASI_Link': 'https://www.msci.com/our-soluti...
Meta Platforms            {'MASI_Link': 'https://www.msci.com/our-soluti...
Bank of America           {'MASI_Link': 'https://www.msci.com/our-soluti...
Dell Technologies         {'MASI_Link': 'https://www.msci.com/our-soluti...
Archer Daniels Midland    {'MASI_Link': 'https://www.msci.com/our-soluti...
Citigroup                 {'MASI_Link': 'https://www.msci.com/our-soluti...
United Parcel Service     {'MASI_Link': 'https://www.msci.com/our-soluti...
Pfizer                    {'MASI_Link': 'https://www.msci.com/our-soluti...
Johnson & Johnson         {'MASI_Link': 'https://www.msci.com/our-soluti...
FedEx                     {'MASI_Link': 'https://www.msci.com/our-soluti...
PepsiCo                   {'MASI_Link': 'https://www.msci.com/our-soluti...
Walt Disney               {'MASI_Link': 'https://www.msci.com/our-soluti...
Tesla                     {'MASI_Link': 'https://www.msci.com/our-soluti...
PROCTER & GAMBLE          {'MASI_Link': 'https://www.msci.com/our-soluti...
General Electric          {'MASI_Link': 'https://www.msci.com/our-soluti...
METLIFE                   {'MASI_Link': 'https://www.msci.com/our-soluti...
Goldman Sachs Group       {'MASI_Link': 'https://www.msci.com/our-soluti...
Boeing                    {'MASI_Link': 'https://www.msci.com/our-soluti...
Lockheed Martin           {'MASI_Link': 'https://www.msci.com/our-soluti...
Morgan Stanley            {'MASI_Link': 'https://www.msci.com/our-soluti...
Caterpillar               {'MASI_Link': 'https://www.msci.com/our-soluti...
AbbVie                    {'MASI_Link': 'https://www.msci.com/our-soluti...
Tyson Foods               {'MASI_Link': 'https://www.msci.com/our-soluti...
Cisco Systems             {'MASI_Link': 'https://www.msci.com/our-soluti...
ALLSTATE                  {'MASI_Link': 'https://www.msci.com/our-soluti...

In [9]:
esg_ratings_msci[indicators] = esg_ratings_msci.apply(
    lambda x: [x['MSCI'][key] for key in indicators],
    axis=1,
    result_type='expand'
    )

msci_mapping = {
    'lead': (10.0+7.1)/2*10,
    'average':  (7.1+2.8)/2*10,
    'lag': (2.8+0.0)/2*10
}

/var/folders/lv/slw57q717v398wpsx73c3dxh0000gn/T/ipykernel_37732/3173393665.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  esg_ratings_msci[indicators] = esg_ratings_msci.apply(
/var/folders/lv/slw57q717v398wpsx73c3dxh0000gn/T/ipykernel_37732/3173393665.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  esg_ratings_msci[indicators] = esg_ratings_msci.apply(

In [10]:
msci_mapping

{'lead': 85.5, 'average': 49.49999999999999, 'lag': 14.0}

In [11]:
esg_ratings_msci.head()

,MSCI,Corporate_Behavior,Corporate_Governance,Human_Capital_Development,Carbon_Emissions,Privacy_Data_Security
Company,,,,,,
Tencent Holdings,{'MASI_Link': 'https://www.msci.com/our-soluti...,lag,average,average,average,lead
Walmart,{'MASI_Link': 'https://www.msci.com/our-soluti...,lag,average,average,average,average
Amazon,{'MASI_Link': 'https://www.msci.com/our-soluti...,lag,average,average,lead,average
Exxon Mobil,{'MASI_Link': 'https://www.msci.com/our-soluti...,average,average,lead,average,average
Apple,{'MASI_Link': 'https://www.msci.com/our-soluti...,lag,lead,average,lag,average

In [12]:

esg_ratings_sp[dimensions] = esg_ratings_sp.apply(
    # lambda x: [x['Dimensions'][key] for key in dimensions],
    lambda x: [x['SPGlobal'][key] for key in dimensions],

    axis=1,
    result_type='expand'
    )

/var/folders/lv/slw57q717v398wpsx73c3dxh0000gn/T/ipykernel_37732/2396172895.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  esg_ratings_sp[dimensions] = esg_ratings_sp.apply(
/var/folders/lv/slw57q717v398wpsx73c3dxh0000gn/T/ipykernel_37732/2396172895.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  esg_ratings_sp[dimensions] = esg_ratings_sp.apply(

In [13]:
esg_ratings_sp.head()

,SPGlobal,Human_Capital_Management,Business_Ethics,Climate_Strategy,Customer_Relations
Company,,,,,
Tencent Holdings,{'SPGlobal_link': 'https://www.spglobal.com/es...,66,47,70,72
Walmart,{'SPGlobal_link': 'https://www.spglobal.com/es...,63,72,99,19
Amazon,{'SPGlobal_link': 'https://www.spglobal.com/es...,17,45,56,8
Exxon Mobil,{'SPGlobal_link': 'https://www.spglobal.com/es...,22,53,39,33
Apple,{'SPGlobal_link': 'https://www.spglobal.com/es...,22,25,39,23

In [14]:
esg_ratings_msci.head()

,MSCI,Corporate_Behavior,Corporate_Governance,Human_Capital_Development,Carbon_Emissions,Privacy_Data_Security
Company,,,,,,
Tencent Holdings,{'MASI_Link': 'https://www.msci.com/our-soluti...,lag,average,average,average,lead
Walmart,{'MASI_Link': 'https://www.msci.com/our-soluti...,lag,average,average,average,average
Amazon,{'MASI_Link': 'https://www.msci.com/our-soluti...,lag,average,average,lead,average
Exxon Mobil,{'MASI_Link': 'https://www.msci.com/our-soluti...,average,average,lead,average,average
Apple,{'MASI_Link': 'https://www.msci.com/our-soluti...,lag,lead,average,lag,average

In [15]:
df_msci = esg_ratings_msci.melt(
    ignore_index=False, 
    value_vars=indicators, 
    var_name='dimension', 
    value_name='rating')
df_msci.reset_index(inplace=True)
df_msci['score'] = df_msci['rating'].map(msci_mapping)

In [16]:
df_msci

              Company              dimension   rating  score
0    Tencent Holdings     Corporate_Behavior      lag   14.0
1             Walmart     Corporate_Behavior      lag   14.0
2              Amazon     Corporate_Behavior      lag   14.0
3         Exxon Mobil     Corporate_Behavior  average   49.5
4               Apple     Corporate_Behavior      lag   14.0
..                ...                    ...      ...    ...
250       Caterpillar  Privacy_Data_Security      lag   14.0
251            AbbVie  Privacy_Data_Security     lead   85.5
252       Tyson Foods  Privacy_Data_Security     lead   85.5
253     Cisco Systems  Privacy_Data_Security  average   49.5
254          ALLSTATE  Privacy_Data_Security  average   49.5

[255 rows x 4 columns]

In [17]:
df_spglobal = esg_ratings_sp.melt(
    ignore_index=False, 
    value_vars=dimensions, 
    var_name='dimension', 
    value_name='score')
df_spglobal.reset_index(inplace=True)
df_spglobal.head()

            Company                 dimension  score
0  Tencent Holdings  Human_Capital_Management     66
1           Walmart  Human_Capital_Management     63
2            Amazon  Human_Capital_Management     17
3       Exxon Mobil  Human_Capital_Management     22
4             Apple  Human_Capital_Management     22

In [18]:
df_div = pd.read_json('/Users/chenwanqiu/Downloads/llm_esg_judge-2_/submission/Task2_Analysis/esg_divergence.json')

df_div.head()

            company  divergence
0  Tencent Holdings           7
1    Meta Platforms           9
2             Apple           8
3     Cisco Systems           3
4         Microsoft           6

To visualize the ESG ratings and their divergence for different groups, we will create a series of plots. Each group, defined by the divergence range, will have its own set of subplots. Specifically, we will generate one radar plot for each ESG rating provider (MSCI and S&P Global) and a scatter plot for the divergence. All subplots will share the same legend for consistency and ease of comparison. The divergence groups are categorized as follows: low (1-3), middle (4-6), and high (7-10). This approach will help us understand the ESG ratings and their divergence across different companies and rating providers.

In [19]:
from plotly.subplots import make_subplots

import plotly.graph_objects as go
import plotly.express as px
import os

def plot_radar_chart(df):
    return px.line_polar(
        df, 
        r="score", 
        theta="dimension", 
        color="Company", 
        line_close=True
        )  


def plot_rating_divergence(
        sector,
        industry,
        msci, 
        spglobal, 
        divergence, 
        divergence_min, 
        divergence_max
        ):
    companies = divergence[divergence.apply(
        lambda x: divergence_min<=x['divergence']<=divergence_max, axis=1
        )]['company']
    
    if not companies.any():
        print('No companies found in the given divergence range.')
        return
    df_msci = msci[msci['Company'].isin(companies)]
    df_spglobal = spglobal[spglobal['Company'].isin(companies)]
    df_div = divergence[divergence['company'].isin(companies)]
    # Create separate radar charts for MSCI indicators and S&P dimensions
    fig = make_subplots(rows=2, cols=2, 
                        specs=[[{'type': 'polar'}, {'type': 'polar'}],
                                [ {'type': 'scatter', "colspan": 2}, None]],
                        subplot_titles=("MSCI Indicators", "S&P Dimensions"))

    # Add MSCI indicators trace
    fig11 = plot_radar_chart(df_msci)
    for trace in fig11.data:
        fig.add_trace(trace, row=1, col=1)

    fig12 = plot_radar_chart(df_spglobal)
    for trace in fig12.data:
        fig.add_trace(trace, row=1, col=2)

    fig.update_traces(legendgroup='group1',showlegend=False, row=1, col=2)
                   
    fig13 = px.scatter(df_div, x='company', y='divergence', size='divergence', color='company')
    for trace in fig13.data:
        fig.add_trace(trace, row=2, col=1)
    fig.update_traces(legendgroup='group1',showlegend=False, row=2, col=1)

    # Customize the layout
    fig.update_layout(
        title='ESG Ratings Comparison (Spider Chart)',
        title_font_size=20,
        title_x=0.5,  # Center the title
        showlegend=True,
        legend=dict(
            orientation="h",  # Horizontal legend
            yanchor="bottom",
            y=1.02,
            xanchor="right",
            x=1
        ),
        height=800 , # Increase the height of the plot
        width=800  # Increase the width of the plot
    )
    folder = f'/Users/chenwanqiu/Downloads/llm_esg_judge-2_/submission/Task3_Visualisation/{sector}/{industry}'
    os.makedirs(folder, exist_ok=True)
    fig.write_html(f'{folder}/esg_ratings_comparison_divergence_{divergence_min}_{divergence_max}.html')
    # Show the chart
    fig.show()


sector = "Technology"
industry = "Internet Services and Retailing"
for div_min, div_max in [(1, 3), (4, 6), (7, 10)]:
    plot_rating_divergence(sector, industry, df_msci, df_spglobal, df_div, div_min, div_max)